Repository zingolabs/zingolib, pull requests merged in 2024-10, with the labels that each got.

#1434 simplify load_example_wallet match
  zingolib/src/wallet/disk/testing/examples.rs
Labels: good first issue, lower priority, refactor only

#1414 Unify keys
  Cargo.lock
  libtonode-tests/tests/concrete.rs
  zingolib/Cargo.toml
  zingolib/src/blaze/trial_decryptions.rs
  zingolib/src/commands.rs
  zingolib/src/lightclient.rs
  zingolib/src/testutils.rs
  zingolib/src/wallet.rs
  zingolib/src/wallet/describe.rs
  zingolib/src/wallet/disk.rs
  zingolib/src/wallet/disk/testing.rs
  zingolib/src/wallet/disk/testing/tests.rs
  zingolib/src/wallet/error.rs
  zingolib/src/wallet/keys.rs
  zingolib/src/wallet/keys/legacy.rs
  zingolib/src/wallet/keys/legacy/extended_transparent.rs
  zingolib/src/wallet/keys/unified.rs
  zingolib/src/wallet/notes/interface.rs
  zingolib/src/wallet/traits.rs
  zingolib/src/wallet/transaction_context.rs
  zingolib/src/wallet/transaction_record.rs
Labels: 320

#1474 Explicit Invocation of thiserror::Error macro
  zingo-netutils/src/lib.rs
  zingolib/src/lightclient/send.rs
  zingolib/src/utils/conversion.rs
  zingolib/src/wallet/error.rs
  zingolib/src/wallet/propose.rs
  zingolib/src/wallet/send.rs
  zingolib/src/wallet/transaction_records_by_id/trait_inputsource.rs
  zingolib/src/wallet/tx_map.rs
Labels: refactor only

#1484 Helperize truncate
  libtonode-tests/tests/concrete.rs
  zingolib/src/data/witness_trees.rs
  zingolib/src/wallet/traits.rs
  zingolib/src/wallet/tx_map/recording.rs
  zingolib/src/wallet/witnesses.rs
Labels: refactor only

#1478 Main bc owl mainnet 3
  Cargo.lock
  libtonode-tests/tests/wallet.rs
  zingolib/Cargo.toml
  zingolib/src/lightclient/send.rs
  zingolib/src/lightclient/sync.rs
  zingolib/src/testutils/assertions.rs
  zingolib/src/testutils/chain_generics/with_assertions.rs
  zingolib/src/testutils/lightclient.rs
  zingolib/src/wallet/disk/testing/examples.rs
  zingolib/src/wallet/disk/testing/examples/mainnet/hhcclaltpcckcsslpcnetblr/latest/zingo-wallet.dat
  zingolib/src/wallet/disk/testing/tests.rs
  zingolib/src/wallet/propose.rs
Labels: test

#1475 Handle start mempool monitor
  libtonode-tests/tests/concrete.rs
  zingocli/src/lib.rs
  zingolib/src/lightclient/sync.rs
  zingolib/src/testutils/chain_generics/fixtures.rs
Labels: refactor only
